[bar/mybar]
; Posició i mida
width = 100%
height = 27
position = top
background = #1e1e2e
foreground = #cdd6f4

; Font
font-0 = monospace:size=10

; Mòduls que apareixen a la barra
modules-left = date
modules-center = cpu
modules-right = memory

; ============ MÒDULS ============
[module/date]
type = internal/date
interval = 1
; Format de data i hora
date = %d/%m/%Y %H:%M

[module/cpu]
type = internal/cpu
interval = 2
; Mostra l'ús de la CPU
label = CPU: %percentage%%

[module/memory]
type = internal/memory
interval = 2
; Mostra la memòria usada
label = RAM: %percentage_used%%
